# Generated by Django 5.2.7 on 2025-10-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Nhập nhiều tag, cách nhau bằng dấu phẩy (,)', max_length=200)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('dia_chi', models.CharField(blank=True, max_length=255)),
                ('luot_xem', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản')], default='draft', max_length=20)),
            ],
        ),
    ]
