# Generated by Django 5.2.7 on 2025-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], max_length=20),
        ),
    ]
