# Generated by Django 5.2.7 on 2025-10-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_lat_home_lon_alter_home_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'InActive')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
